### PR TITLE
[Chat] Visual Cleanup - Round 1

### PR DESCRIPTION
**Pull request by hellogerard**
### Summary

This PR fixes the following random visual issues in Chat.

1. Chat left/right padding inconsistent ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3062988841])).

1. Update the list of reaction emojis ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061355416)).

1. Shrink message text input ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061713067)) and enlarge Send button ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061708579)).

1. Update background for ReactionsList and ReactionPicker ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061415668)).

1. Change how to take actions on messages and users ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061354110)).
    - Tapping on a message brings up ReactionPicker.
    - Long pressing on a message brings up action sheet with message-only actions.
    - Long pressing on an avatar brings up action sheet with user-only actions.

1. Make it easier to dismiss keyboard ([Basecamp](https://3.basecamp.com/3926363/buckets/17566548/todos/3061352504)).

### Discussion

1. ~Using an `envelope` icon for the Send button temporarily. When we get a `paper-airplane` icon, will swap it in in a future PR.~

### Testing

(Same items as above.)

1. Check that left/right padding in main messages window is even.
1. Check that the reactions emoji list is what is in the Basecamp todo (only positive emojis).
1. Thoughts on the new message input?
1. Check that the background color for the ReactionsList and ReactionPicker is light in light mode and dark in dark mode.
1. Check that tapping a message brings up reaction picker. Check that long pressing messages bring up message actions and long pressing avatars brings up user actions. Note that long pressing on yourself does nothing because there are no user actions to take on yourself.
1. Play around with dismissing the keyboard to see how it feels.

### Screenshots

Correct padding, new emojis, new text input, correct reactions background.

|Light mode|Dark mode|
|---|---|
|Screen Shot 2020-09-28 at 11 07 40 PM|Screen Shot 2020-09-29 at 9 42 28 AM|

### CODE REVIEW

**Comment by jordanwade** [comment]
Question: I'm on iOS 12.4.7 on my personal iPhone 6, super old I know 😬 . My guess is that since the video always goes full screen for me I can't see if the chat is working. What versions of iOS are we supporting for chat/events? Going to check the sim version now.

**Comment by rkdavidson** [comment]
Since I'm still blocked by Xcode update nonsense for local testing/builds, I marked up some visual feedback based off the screenshots.

I trust your call @hellogerard on what is worth doing based off effort, nothing is show stopper.
Just calling out opportunities for visual polish.
Things marked in **red** bug me more than the things marked in **orange**, FWIW.

If you prefer, we can ship this PR — assuming @jordanwade's testing didn't find any major showstoppers — and see what we can get to in the next one.

**Visual QA:**
1. Internal padding on messages should be ~1–2 character's width for visual breathing room.
2. This specific situation may be edge casey, but the two bubbles got really close together here... if possible, some margin or way to prevent this would be nice
3. The all-emojis bubble looks a bit funky at the bottom
4. The placeholder text isn't _perfectly_ vertically centered within the Message Input area — but I had this issue on web too, and it wasn't trivial to fiddle with.
5. The name/date text is still using system sans instead of Gotham
6. Could use a handful of pixels margin between name/date and the text bubble
7. The horizontal padding in the MessagesList could be increased slightly so the avatars sit on the guidelines created by the MessageInput... but typing this up, this is super low priority and might be overly OCD

|Screenshot 1|Screenshot 2 (with typography tweak)|
|---|---|
|Feedback1|Feedback2|

**Comment by hellogerard** [comment]
@jordanwade I'm not sure if it's the iOS version. I've run into that intermittently and it felt like a feature flag issue. If you're not in the security group, it will open the normal Media Player, which is full screen. If you are, then it opens the Media Player with chat. In the sim, reloading or logging out/in seems to fix it. Does any of that work?

**Comment by jordanwade** [comment]
@hellogerard The only thing I'm seeing is that I can add reactions to my own messages. Everything else seems to be working as expected and looks good to me.
IMG_4B4B43CA12C6-1

IMG_E6700D62F9F8-1

**Review by jordanwade — APPROVED** [review]

**Comment by hellogerard** [comment]
> Since I'm still blocked by Xcode update nonsense for local testing/builds, I marked up some visual feedback based off the screenshots.

@rkdavidson I can get most of these.

**Comment by rkdavidson** [comment]
Sorry for the unconsolidated feedback @hellogerard , but — is it easy to change the text color for avatar initials?

**Comment by hellogerard** [comment]
I think I got everything. I had the avatar initials already in a fix!

Only thing I wasn't sure of was the ReactionsPicker. It's pops up over top of everything else absolutely positioned, but it has the same background color as my message bubbles. That's why it looks funny. I added a hairline border, which you can see in the pic. Don't love it, but gives it that boundary.

image

**Comment by rkdavidson** [comment]
Ah, that makes way more sense! I didn't realize that was the reactions popover.
Looking _much_ better, @hellogerard 🎉.

Shall we merge?

**Pull request merged**
