### PR TITLE
Groups patch work

### PR DESCRIPTION
**Pull request by asleepingpanda**

### CODE REVIEW

**Review by jordanwade — APPROVED** [review]

**Comment by jordanwade** [comment]
@asleepingpanda are there any changes needed in Rock?

**Comment by jordanwade** [comment]
@burkeshartsis do we need to do anything before merging? Considering you have changes to the resources UI?

**Comment by asleepingpanda** [comment]
@jordanwade Rock is good to go on this one. The only other consideration is that PR for the API before this can be merged

**Comment by asleepingpanda** [comment]
@jordanwade I'm gonna go ahead and merge this now.

**Pull request merged**
