### PR TITLE
Upgrade to Apollos 1.6.0

### PR DESCRIPTION
**Pull request by asleepingpanda**
Some things to consider:

* CF is not ready for the Fastlane integration right now, so we're opting out until we can plan some time to get that set up (Zoom considerations needed with @jordanwade )
* Big update to the way that Features Feeds are handled in the app. Should refresh in a more stable way and load data more reliably
* Deprecate and remove the `react-native-dark-mode` package in favor of the Core Apollos `react-native-appearance`

### CODE REVIEW

**Comment by asleepingpanda** [comment]
@jordanwade can you pull these changes and try running? I'm getting a error on `postinstall` and can't run the app. I think it might be related to a gemfile issue, but I'm not 100%

**Comment by asleepingpanda** [comment]
@rkdavidson and/or @jordanwade could I get a quick review on this guy so we can merge it in preparation for release??

**Comment by rkdavidson** [comment]
Hey @asleepingpanda , I started looking through the code changes but haven't tested the changes yet. Just left to grab some lunch, but can do more through testing in a bit unless you're confident enough to merge?

**Comment by jordanwade** [comment]
@asleepingpanda I'm seeing this error, is this expected? 
image

**Comment by jordanwade** [comment]
nm, I think `pod repo update` seems to be the fix

**Comment by jordanwade** [comment]
@asleepingpanda I think everything is working ok. Only think that I'm seeing is that the `live` flag isn't showing up on live events. But, I'm not sure that if that is related to this PR or a Rock/Caching issue. 
image

**Review by jordanwade — APPROVED** [review]
Besides that `live` flag issue I mentioned everything seems to be working correctly smoke testing this PR.

**Comment by rkdavidson** [comment]
@jordanwade I believe the live events not being live is a Rock side thing, sounds like they were visible to everyone so the live stream schedule was temporarily removed.

**Comment by asleepingpanda** [comment]
@jordanwade yeah so I had the exact same thing happen to me with OneSignal. Running that exact command you ran fixed it for me as well.

And @rkdavidson is correct. We've got Live Streams temporarily disabled

**Pull request merged**
